name: danaid
description: Healthcare application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+210020028

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_screenutil: ^5.0.0
  google_fonts: ^2.0.0
  shared_preferences: ^2.0.4
  provider: ^6.0.2
  get_it: ^7.2.0
  connectivity: null
  line_icons: null
  cached_network_image: ^3.0.0
  intl: null
  font_awesome_flutter: ^9.2.0
  flutter_vector_icons: ^1.0.0
  #freezed: ^0.14.3
  simple_moment: null
  percent_indicator: null
  simple_animations: null
  flutter_share: ^2.0.0
  flutter_svg: ^1.0.3
  google_maps_flutter: ^2.1.2
  material_design_icons_flutter: ^5.0.6595
  carousel_slider: null
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  country_pickers: ^2.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4+8
  path_provider: ^2.0.1
  location: ^4.1.1
  file_picker: ^4.3.3
  table_calendar: ^3.0.0
  intl_phone_number_input: ^0.7.0+1
  autocomplete_textfield_ns: ^2.0.0
  simple_tags: ^0.0.4
  qrscan2: ^0.1.0
  permission_handler: ^8.3.0
  swipe_to_action: ^0.2.0
  url_launcher: ^6.0.3
  flutter_google_places: ^0.3.0
  pretty_qr_code: ^2.0.1
  coast: ^2.0.1
  fl_chart: ^0.36.1
  firebase_in_app_messaging: ^0.6.0+6
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.2.0
  firebase_dynamic_links: ^4.0.4
  share: ^2.0.4
  agora_rtc_engine: ^5.2.0
  dio: ^4.0.0
  http: ^0.13.3
  expansion_tile_card: ^2.0.0
  flutterwave: ^1.0.1
  flutterwave_standard: ^1.0.3
  fluttertoast: ^8.0.9
  go_router: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  hive_generator: ^1.1.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/Two-tone/
    - assets/icons/Bulk/
    #- assets/logos/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
